//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("hotelModel", "ClienteID", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hotel.Models.Cliente), "acompaniantes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hotel.Models.Acompaniantes), true)]
[assembly: EdmRelationshipAttribute("hotelModel", "HabitacionID", "habitacion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hotel.Models.Habitacion), "articulo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hotel.Models.Articulo), true)]
[assembly: EdmRelationshipAttribute("hotelModel", "ClienteID_", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hotel.Models.Cliente), "reserva", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hotel.Models.Reserva), true)]
[assembly: EdmRelationshipAttribute("hotelModel", "HabitacionID_", "habitacion", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Hotel.Models.Habitacion), "reserva", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hotel.Models.Reserva), true)]

#endregion

namespace Hotel.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class hotelEntities5 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto hotelEntities5 usando la cadena de conexión encontrada en la sección 'hotelEntities5' del archivo de configuración de la aplicación.
        /// </summary>
        public hotelEntities5() : base("name=hotelEntities5", "hotelEntities5")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto hotelEntities5.
        /// </summary>
        public hotelEntities5(string connectionString) : base(connectionString, "hotelEntities5")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto hotelEntities5.
        /// </summary>
        public hotelEntities5(EntityConnection connection) : base(connection, "hotelEntities5")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Acompaniantes> Acompaniantes
        {
            get
            {
                if ((_Acompaniantes == null))
                {
                    _Acompaniantes = base.CreateObjectSet<Acompaniantes>("Acompaniantes");
                }
                return _Acompaniantes;
            }
        }
        private ObjectSet<Acompaniantes> _Acompaniantes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Articulo> Articulo
        {
            get
            {
                if ((_Articulo == null))
                {
                    _Articulo = base.CreateObjectSet<Articulo>("Articulo");
                }
                return _Articulo;
            }
        }
        private ObjectSet<Articulo> _Articulo;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Gastos> Gastos
        {
            get
            {
                if ((_Gastos == null))
                {
                    _Gastos = base.CreateObjectSet<Gastos>("Gastos");
                }
                return _Gastos;
            }
        }
        private ObjectSet<Gastos> _Gastos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Habitacion> Habitacion
        {
            get
            {
                if ((_Habitacion == null))
                {
                    _Habitacion = base.CreateObjectSet<Habitacion>("Habitacion");
                }
                return _Habitacion;
            }
        }
        private ObjectSet<Habitacion> _Habitacion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Reserva> Reserva
        {
            get
            {
                if ((_Reserva == null))
                {
                    _Reserva = base.CreateObjectSet<Reserva>("Reserva");
                }
                return _Reserva;
            }
        }
        private ObjectSet<Reserva> _Reserva;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Acompaniantes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAcompaniantes(Acompaniantes acompaniantes)
        {
            base.AddObject("Acompaniantes", acompaniantes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Articulo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToArticulo(Articulo articulo)
        {
            base.AddObject("Articulo", articulo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cliente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Gastos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToGastos(Gastos gastos)
        {
            base.AddObject("Gastos", gastos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Habitacion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToHabitacion(Habitacion habitacion)
        {
            base.AddObject("Habitacion", habitacion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Reserva. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToReserva(Reserva reserva)
        {
            base.AddObject("Reserva", reserva);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Acompaniantes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Acompaniantes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Acompaniantes.
        /// </summary>
        /// <param name="acompanianteID">Valor inicial de la propiedad AcompanianteID.</param>
        /// <param name="clienteID">Valor inicial de la propiedad ClienteID.</param>
        public static Acompaniantes CreateAcompaniantes(global::System.Int32 acompanianteID, global::System.Int32 clienteID)
        {
            Acompaniantes acompaniantes = new Acompaniantes();
            acompaniantes.AcompanianteID = acompanianteID;
            acompaniantes.ClienteID = clienteID;
            return acompaniantes;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcompanianteID
        {
            get
            {
                return _AcompanianteID;
            }
            set
            {
                if (_AcompanianteID != value)
                {
                    OnAcompanianteIDChanging(value);
                    ReportPropertyChanging("AcompanianteID");
                    _AcompanianteID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AcompanianteID");
                    OnAcompanianteIDChanged();
                }
            }
        }
        private global::System.Int32 _AcompanianteID;
        partial void OnAcompanianteIDChanging(global::System.Int32 value);
        partial void OnAcompanianteIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClienteID
        {
            get
            {
                return _ClienteID;
            }
            set
            {
                OnClienteIDChanging(value);
                ReportPropertyChanging("ClienteID");
                _ClienteID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClienteID");
                OnClienteIDChanged();
            }
        }
        private global::System.Int32 _ClienteID;
        partial void OnClienteIDChanging(global::System.Int32 value);
        partial void OnClienteIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Edad
        {
            get
            {
                return _Edad;
            }
            set
            {
                OnEdadChanging(value);
                ReportPropertyChanging("Edad");
                _Edad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Edad");
                OnEdadChanged();
            }
        }
        private global::System.String _Edad;
        partial void OnEdadChanging(global::System.String value);
        partial void OnEdadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombres
        {
            get
            {
                return _Nombres;
            }
            set
            {
                OnNombresChanging(value);
                ReportPropertyChanging("Nombres");
                _Nombres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombres");
                OnNombresChanged();
            }
        }
        private global::System.String _Nombres;
        partial void OnNombresChanging(global::System.String value);
        partial void OnNombresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Apellidos
        {
            get
            {
                return _Apellidos;
            }
            set
            {
                OnApellidosChanging(value);
                ReportPropertyChanging("Apellidos");
                _Apellidos = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Apellidos");
                OnApellidosChanged();
            }
        }
        private global::System.String _Apellidos;
        partial void OnApellidosChanging(global::System.String value);
        partial void OnApellidosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Identificacion
        {
            get
            {
                return _Identificacion;
            }
            set
            {
                OnIdentificacionChanging(value);
                ReportPropertyChanging("Identificacion");
                _Identificacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Identificacion");
                OnIdentificacionChanged();
            }
        }
        private global::System.String _Identificacion;
        partial void OnIdentificacionChanging(global::System.String value);
        partial void OnIdentificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lugar_expedicion
        {
            get
            {
                return _Lugar_expedicion;
            }
            set
            {
                OnLugar_expedicionChanging(value);
                ReportPropertyChanging("Lugar_expedicion");
                _Lugar_expedicion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lugar_expedicion");
                OnLugar_expedicionChanged();
            }
        }
        private global::System.String _Lugar_expedicion;
        partial void OnLugar_expedicionChanging(global::System.String value);
        partial void OnLugar_expedicionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_actual
        {
            get
            {
                return _Fecha_actual;
            }
            set
            {
                OnFecha_actualChanging(value);
                ReportPropertyChanging("Fecha_actual");
                _Fecha_actual = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_actual");
                OnFecha_actualChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_actual;
        partial void OnFecha_actualChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_actualChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hotelModel", "ClienteID", "cliente")]
        public Cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("hotelModel.ClienteID", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("hotelModel.ClienteID", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("hotelModel.ClienteID", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("hotelModel.ClienteID", "cliente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Articulo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Articulo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Articulo.
        /// </summary>
        /// <param name="articuloID">Valor inicial de la propiedad ArticuloID.</param>
        /// <param name="habitacionID">Valor inicial de la propiedad HabitacionID.</param>
        public static Articulo CreateArticulo(global::System.Int32 articuloID, global::System.Int32 habitacionID)
        {
            Articulo articulo = new Articulo();
            articulo.ArticuloID = articuloID;
            articulo.HabitacionID = habitacionID;
            return articulo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ArticuloID
        {
            get
            {
                return _ArticuloID;
            }
            set
            {
                if (_ArticuloID != value)
                {
                    OnArticuloIDChanging(value);
                    ReportPropertyChanging("ArticuloID");
                    _ArticuloID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ArticuloID");
                    OnArticuloIDChanged();
                }
            }
        }
        private global::System.Int32 _ArticuloID;
        partial void OnArticuloIDChanging(global::System.Int32 value);
        partial void OnArticuloIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HabitacionID
        {
            get
            {
                return _HabitacionID;
            }
            set
            {
                OnHabitacionIDChanging(value);
                ReportPropertyChanging("HabitacionID");
                _HabitacionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HabitacionID");
                OnHabitacionIDChanged();
            }
        }
        private global::System.Int32 _HabitacionID;
        partial void OnHabitacionIDChanging(global::System.Int32 value);
        partial void OnHabitacionIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre_articulo
        {
            get
            {
                return _Nombre_articulo;
            }
            set
            {
                OnNombre_articuloChanging(value);
                ReportPropertyChanging("Nombre_articulo");
                _Nombre_articulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre_articulo");
                OnNombre_articuloChanged();
            }
        }
        private global::System.String _Nombre_articulo;
        partial void OnNombre_articuloChanging(global::System.String value);
        partial void OnNombre_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cantidad_articulo
        {
            get
            {
                return _Cantidad_articulo;
            }
            set
            {
                OnCantidad_articuloChanging(value);
                ReportPropertyChanging("Cantidad_articulo");
                _Cantidad_articulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad_articulo");
                OnCantidad_articuloChanged();
            }
        }
        private Nullable<global::System.Int32> _Cantidad_articulo;
        partial void OnCantidad_articuloChanging(Nullable<global::System.Int32> value);
        partial void OnCantidad_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hotelModel", "HabitacionID", "habitacion")]
        public Habitacion habitacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Habitacion>("hotelModel.HabitacionID", "habitacion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Habitacion>("hotelModel.HabitacionID", "habitacion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Habitacion> habitacionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Habitacion>("hotelModel.HabitacionID", "habitacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Habitacion>("hotelModel.HabitacionID", "habitacion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cliente.
        /// </summary>
        /// <param name="clienteID">Valor inicial de la propiedad ClienteID.</param>
        /// <param name="identificacion">Valor inicial de la propiedad Identificacion.</param>
        public static Cliente CreateCliente(global::System.Int32 clienteID, global::System.String identificacion)
        {
            Cliente cliente = new Cliente();
            cliente.ClienteID = clienteID;
            cliente.Identificacion = identificacion;
            return cliente;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClienteID
        {
            get
            {
                return _ClienteID;
            }
            set
            {
                if (_ClienteID != value)
                {
                    OnClienteIDChanging(value);
                    ReportPropertyChanging("ClienteID");
                    _ClienteID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClienteID");
                    OnClienteIDChanged();
                }
            }
        }
        private global::System.Int32 _ClienteID;
        partial void OnClienteIDChanging(global::System.Int32 value);
        partial void OnClienteIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Identificacion
        {
            get
            {
                return _Identificacion;
            }
            set
            {
                OnIdentificacionChanging(value);
                ReportPropertyChanging("Identificacion");
                _Identificacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Identificacion");
                OnIdentificacionChanged();
            }
        }
        private global::System.String _Identificacion;
        partial void OnIdentificacionChanging(global::System.String value);
        partial void OnIdentificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombres
        {
            get
            {
                return _Nombres;
            }
            set
            {
                OnNombresChanging(value);
                ReportPropertyChanging("Nombres");
                _Nombres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombres");
                OnNombresChanged();
            }
        }
        private global::System.String _Nombres;
        partial void OnNombresChanging(global::System.String value);
        partial void OnNombresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nacionalidad
        {
            get
            {
                return _Nacionalidad;
            }
            set
            {
                OnNacionalidadChanging(value);
                ReportPropertyChanging("Nacionalidad");
                _Nacionalidad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nacionalidad");
                OnNacionalidadChanged();
            }
        }
        private global::System.String _Nacionalidad;
        partial void OnNacionalidadChanging(global::System.String value);
        partial void OnNacionalidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lugar_expedicion
        {
            get
            {
                return _Lugar_expedicion;
            }
            set
            {
                OnLugar_expedicionChanging(value);
                ReportPropertyChanging("Lugar_expedicion");
                _Lugar_expedicion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lugar_expedicion");
                OnLugar_expedicionChanged();
            }
        }
        private global::System.String _Lugar_expedicion;
        partial void OnLugar_expedicionChanging(global::System.String value);
        partial void OnLugar_expedicionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dir_residencia
        {
            get
            {
                return _Dir_residencia;
            }
            set
            {
                OnDir_residenciaChanging(value);
                ReportPropertyChanging("Dir_residencia");
                _Dir_residencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dir_residencia");
                OnDir_residenciaChanged();
            }
        }
        private global::System.String _Dir_residencia;
        partial void OnDir_residenciaChanging(global::System.String value);
        partial void OnDir_residenciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cuidad
        {
            get
            {
                return _Cuidad;
            }
            set
            {
                OnCuidadChanging(value);
                ReportPropertyChanging("Cuidad");
                _Cuidad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cuidad");
                OnCuidadChanged();
            }
        }
        private global::System.String _Cuidad;
        partial void OnCuidadChanging(global::System.String value);
        partial void OnCuidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono_fijo
        {
            get
            {
                return _Telefono_fijo;
            }
            set
            {
                OnTelefono_fijoChanging(value);
                ReportPropertyChanging("Telefono_fijo");
                _Telefono_fijo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono_fijo");
                OnTelefono_fijoChanged();
            }
        }
        private global::System.String _Telefono_fijo;
        partial void OnTelefono_fijoChanging(global::System.String value);
        partial void OnTelefono_fijoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono_celular
        {
            get
            {
                return _Telefono_celular;
            }
            set
            {
                OnTelefono_celularChanging(value);
                ReportPropertyChanging("Telefono_celular");
                _Telefono_celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono_celular");
                OnTelefono_celularChanged();
            }
        }
        private global::System.String _Telefono_celular;
        partial void OnTelefono_celularChanging(global::System.String value);
        partial void OnTelefono_celularChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Profesion
        {
            get
            {
                return _Profesion;
            }
            set
            {
                OnProfesionChanging(value);
                ReportPropertyChanging("Profesion");
                _Profesion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Profesion");
                OnProfesionChanged();
            }
        }
        private global::System.String _Profesion;
        partial void OnProfesionChanging(global::System.String value);
        partial void OnProfesionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Emp_donde_labora
        {
            get
            {
                return _Emp_donde_labora;
            }
            set
            {
                OnEmp_donde_laboraChanging(value);
                ReportPropertyChanging("Emp_donde_labora");
                _Emp_donde_labora = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Emp_donde_labora");
                OnEmp_donde_laboraChanged();
            }
        }
        private global::System.String _Emp_donde_labora;
        partial void OnEmp_donde_laboraChanging(global::System.String value);
        partial void OnEmp_donde_laboraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Procedencia
        {
            get
            {
                return _Procedencia;
            }
            set
            {
                OnProcedenciaChanging(value);
                ReportPropertyChanging("Procedencia");
                _Procedencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Procedencia");
                OnProcedenciaChanged();
            }
        }
        private global::System.String _Procedencia;
        partial void OnProcedenciaChanging(global::System.String value);
        partial void OnProcedenciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Destino_final
        {
            get
            {
                return _Destino_final;
            }
            set
            {
                OnDestino_finalChanging(value);
                ReportPropertyChanging("Destino_final");
                _Destino_final = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Destino_final");
                OnDestino_finalChanged();
            }
        }
        private global::System.String _Destino_final;
        partial void OnDestino_finalChanging(global::System.String value);
        partial void OnDestino_finalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Motivo_del_viaje
        {
            get
            {
                return _Motivo_del_viaje;
            }
            set
            {
                OnMotivo_del_viajeChanging(value);
                ReportPropertyChanging("Motivo_del_viaje");
                _Motivo_del_viaje = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Motivo_del_viaje");
                OnMotivo_del_viajeChanged();
            }
        }
        private global::System.String _Motivo_del_viaje;
        partial void OnMotivo_del_viajeChanging(global::System.String value);
        partial void OnMotivo_del_viajeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Clase_vehiculo
        {
            get
            {
                return _Clase_vehiculo;
            }
            set
            {
                OnClase_vehiculoChanging(value);
                ReportPropertyChanging("Clase_vehiculo");
                _Clase_vehiculo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Clase_vehiculo");
                OnClase_vehiculoChanged();
            }
        }
        private global::System.String _Clase_vehiculo;
        partial void OnClase_vehiculoChanging(global::System.String value);
        partial void OnClase_vehiculoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Marca
        {
            get
            {
                return _Marca;
            }
            set
            {
                OnMarcaChanging(value);
                ReportPropertyChanging("Marca");
                _Marca = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Marca");
                OnMarcaChanged();
            }
        }
        private global::System.String _Marca;
        partial void OnMarcaChanging(global::System.String value);
        partial void OnMarcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Placa
        {
            get
            {
                return _Placa;
            }
            set
            {
                OnPlacaChanging(value);
                ReportPropertyChanging("Placa");
                _Placa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Placa");
                OnPlacaChanged();
            }
        }
        private global::System.String _Placa;
        partial void OnPlacaChanging(global::System.String value);
        partial void OnPlacaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hotelModel", "ClienteID", "acompaniantes")]
        public EntityCollection<Acompaniantes> acompaniantes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Acompaniantes>("hotelModel.ClienteID", "acompaniantes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Acompaniantes>("hotelModel.ClienteID", "acompaniantes", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hotelModel", "ClienteID_", "reserva")]
        public EntityCollection<Reserva> reserva
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reserva>("hotelModel.ClienteID_", "reserva");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reserva>("hotelModel.ClienteID_", "reserva", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Gastos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gastos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Gastos.
        /// </summary>
        /// <param name="gastosID">Valor inicial de la propiedad GastosID.</param>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        public static Gastos CreateGastos(global::System.Int32 gastosID, global::System.DateTime fecha)
        {
            Gastos gastos = new Gastos();
            gastos.GastosID = gastosID;
            gastos.Fecha = fecha;
            return gastos;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GastosID
        {
            get
            {
                return _GastosID;
            }
            set
            {
                if (_GastosID != value)
                {
                    OnGastosIDChanging(value);
                    ReportPropertyChanging("GastosID");
                    _GastosID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GastosID");
                    OnGastosIDChanged();
                }
            }
        }
        private global::System.Int32 _GastosID;
        partial void OnGastosIDChanging(global::System.Int32 value);
        partial void OnGastosIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Items
        {
            get
            {
                return _Items;
            }
            set
            {
                OnItemsChanging(value);
                ReportPropertyChanging("Items");
                _Items = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Items");
                OnItemsChanged();
            }
        }
        private global::System.String _Items;
        partial void OnItemsChanging(global::System.String value);
        partial void OnItemsChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cantidad_items
        {
            get
            {
                return _Cantidad_items;
            }
            set
            {
                OnCantidad_itemsChanging(value);
                ReportPropertyChanging("Cantidad_items");
                _Cantidad_items = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad_items");
                OnCantidad_itemsChanged();
            }
        }
        private Nullable<global::System.Int32> _Cantidad_items;
        partial void OnCantidad_itemsChanging(Nullable<global::System.Int32> value);
        partial void OnCantidad_itemsChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private global::System.String _Precio;
        partial void OnPrecioChanging(global::System.String value);
        partial void OnPrecioChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Habitacion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Habitacion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Habitacion.
        /// </summary>
        /// <param name="habitacionID">Valor inicial de la propiedad HabitacionID.</param>
        /// <param name="precio_habitacion">Valor inicial de la propiedad Precio_habitacion.</param>
        public static Habitacion CreateHabitacion(global::System.Int32 habitacionID, global::System.Int32 precio_habitacion)
        {
            Habitacion habitacion = new Habitacion();
            habitacion.HabitacionID = habitacionID;
            habitacion.Precio_habitacion = precio_habitacion;
            return habitacion;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HabitacionID
        {
            get
            {
                return _HabitacionID;
            }
            set
            {
                if (_HabitacionID != value)
                {
                    OnHabitacionIDChanging(value);
                    ReportPropertyChanging("HabitacionID");
                    _HabitacionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HabitacionID");
                    OnHabitacionIDChanged();
                }
            }
        }
        private global::System.Int32 _HabitacionID;
        partial void OnHabitacionIDChanging(global::System.Int32 value);
        partial void OnHabitacionIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Precio_habitacion
        {
            get
            {
                return _Precio_habitacion;
            }
            set
            {
                OnPrecio_habitacionChanging(value);
                ReportPropertyChanging("Precio_habitacion");
                _Precio_habitacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio_habitacion");
                OnPrecio_habitacionChanged();
            }
        }
        private global::System.Int32 _Precio_habitacion;
        partial void OnPrecio_habitacionChanging(global::System.Int32 value);
        partial void OnPrecio_habitacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Num_habitacion
        {
            get
            {
                return _Num_habitacion;
            }
            set
            {
                OnNum_habitacionChanging(value);
                ReportPropertyChanging("Num_habitacion");
                _Num_habitacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Num_habitacion");
                OnNum_habitacionChanged();
            }
        }
        private global::System.String _Num_habitacion;
        partial void OnNum_habitacionChanging(global::System.String value);
        partial void OnNum_habitacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Num_piso
        {
            get
            {
                return _Num_piso;
            }
            set
            {
                OnNum_pisoChanging(value);
                ReportPropertyChanging("Num_piso");
                _Num_piso = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Num_piso");
                OnNum_pisoChanged();
            }
        }
        private global::System.String _Num_piso;
        partial void OnNum_pisoChanging(global::System.String value);
        partial void OnNum_pisoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hotelModel", "HabitacionID", "articulo")]
        public EntityCollection<Articulo> articulo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Articulo>("hotelModel.HabitacionID", "articulo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Articulo>("hotelModel.HabitacionID", "articulo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hotelModel", "HabitacionID_", "reserva")]
        public EntityCollection<Reserva> reserva
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reserva>("hotelModel.HabitacionID_", "reserva");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reserva>("hotelModel.HabitacionID_", "reserva", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Reserva")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reserva : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Reserva.
        /// </summary>
        /// <param name="reservacionID">Valor inicial de la propiedad ReservacionID.</param>
        /// <param name="clienteID_">Valor inicial de la propiedad ClienteID_.</param>
        public static Reserva CreateReserva(global::System.Int32 reservacionID, global::System.Int32 clienteID_)
        {
            Reserva reserva = new Reserva();
            reserva.ReservacionID = reservacionID;
            reserva.ClienteID_ = clienteID_;
            return reserva;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReservacionID
        {
            get
            {
                return _ReservacionID;
            }
            set
            {
                if (_ReservacionID != value)
                {
                    OnReservacionIDChanging(value);
                    ReportPropertyChanging("ReservacionID");
                    _ReservacionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReservacionID");
                    OnReservacionIDChanged();
                }
            }
        }
        private global::System.Int32 _ReservacionID;
        partial void OnReservacionIDChanging(global::System.Int32 value);
        partial void OnReservacionIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClienteID_
        {
            get
            {
                return _ClienteID_;
            }
            set
            {
                OnClienteID_Changing(value);
                ReportPropertyChanging("ClienteID_");
                _ClienteID_ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClienteID_");
                OnClienteID_Changed();
            }
        }
        private global::System.Int32 _ClienteID_;
        partial void OnClienteID_Changing(global::System.Int32 value);
        partial void OnClienteID_Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HabitacionID_
        {
            get
            {
                return _HabitacionID_;
            }
            set
            {
                OnHabitacionID_Changing(value);
                ReportPropertyChanging("HabitacionID_");
                _HabitacionID_ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HabitacionID_");
                OnHabitacionID_Changed();
            }
        }
        private Nullable<global::System.Int32> _HabitacionID_;
        partial void OnHabitacionID_Changing(Nullable<global::System.Int32> value);
        partial void OnHabitacionID_Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_ingreso
        {
            get
            {
                return _Fecha_ingreso;
            }
            set
            {
                OnFecha_ingresoChanging(value);
                ReportPropertyChanging("Fecha_ingreso");
                _Fecha_ingreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_ingreso");
                OnFecha_ingresoChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_ingreso;
        partial void OnFecha_ingresoChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_ingresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Hora_ingreso
        {
            get
            {
                return _Hora_ingreso;
            }
            set
            {
                OnHora_ingresoChanging(value);
                ReportPropertyChanging("Hora_ingreso");
                _Hora_ingreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hora_ingreso");
                OnHora_ingresoChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Hora_ingreso;
        partial void OnHora_ingresoChanging(Nullable<global::System.TimeSpan> value);
        partial void OnHora_ingresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_egreso
        {
            get
            {
                return _Fecha_egreso;
            }
            set
            {
                OnFecha_egresoChanging(value);
                ReportPropertyChanging("Fecha_egreso");
                _Fecha_egreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_egreso");
                OnFecha_egresoChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_egreso;
        partial void OnFecha_egresoChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_egresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Hora_egreso
        {
            get
            {
                return _Hora_egreso;
            }
            set
            {
                OnHora_egresoChanging(value);
                ReportPropertyChanging("Hora_egreso");
                _Hora_egreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hora_egreso");
                OnHora_egresoChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Hora_egreso;
        partial void OnHora_egresoChanging(Nullable<global::System.TimeSpan> value);
        partial void OnHora_egresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cantidad_dias
        {
            get
            {
                return _Cantidad_dias;
            }
            set
            {
                OnCantidad_diasChanging(value);
                ReportPropertyChanging("Cantidad_dias");
                _Cantidad_dias = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad_dias");
                OnCantidad_diasChanged();
            }
        }
        private Nullable<global::System.Int32> _Cantidad_dias;
        partial void OnCantidad_diasChanging(Nullable<global::System.Int32> value);
        partial void OnCantidad_diasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _Total;
        partial void OnTotalChanging(Nullable<global::System.Int32> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Abono
        {
            get
            {
                return _Abono;
            }
            set
            {
                OnAbonoChanging(value);
                ReportPropertyChanging("Abono");
                _Abono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Abono");
                OnAbonoChanged();
            }
        }
        private Nullable<global::System.Int32> _Abono;
        partial void OnAbonoChanging(Nullable<global::System.Int32> value);
        partial void OnAbonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Restante
        {
            get
            {
                return _Restante;
            }
            set
            {
                OnRestanteChanging(value);
                ReportPropertyChanging("Restante");
                _Restante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Restante");
                OnRestanteChanged();
            }
        }
        private Nullable<global::System.Int32> _Restante;
        partial void OnRestanteChanging(Nullable<global::System.Int32> value);
        partial void OnRestanteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_creacion
        {
            get
            {
                return _Fecha_creacion;
            }
            set
            {
                OnFecha_creacionChanging(value);
                ReportPropertyChanging("Fecha_creacion");
                _Fecha_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_creacion");
                OnFecha_creacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_creacion;
        partial void OnFecha_creacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP_creacion
        {
            get
            {
                return _IP_creacion;
            }
            set
            {
                OnIP_creacionChanging(value);
                ReportPropertyChanging("IP_creacion");
                _IP_creacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP_creacion");
                OnIP_creacionChanged();
            }
        }
        private global::System.String _IP_creacion;
        partial void OnIP_creacionChanging(global::System.String value);
        partial void OnIP_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String User_creacion
        {
            get
            {
                return _User_creacion;
            }
            set
            {
                OnUser_creacionChanging(value);
                ReportPropertyChanging("User_creacion");
                _User_creacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User_creacion");
                OnUser_creacionChanged();
            }
        }
        private global::System.String _User_creacion;
        partial void OnUser_creacionChanging(global::System.String value);
        partial void OnUser_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_ultima_modificacion
        {
            get
            {
                return _Fecha_ultima_modificacion;
            }
            set
            {
                OnFecha_ultima_modificacionChanging(value);
                ReportPropertyChanging("Fecha_ultima_modificacion");
                _Fecha_ultima_modificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_ultima_modificacion");
                OnFecha_ultima_modificacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_ultima_modificacion;
        partial void OnFecha_ultima_modificacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_ultima_modificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP_modificacion
        {
            get
            {
                return _IP_modificacion;
            }
            set
            {
                OnIP_modificacionChanging(value);
                ReportPropertyChanging("IP_modificacion");
                _IP_modificacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP_modificacion");
                OnIP_modificacionChanged();
            }
        }
        private global::System.String _IP_modificacion;
        partial void OnIP_modificacionChanging(global::System.String value);
        partial void OnIP_modificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String User_modificacion
        {
            get
            {
                return _User_modificacion;
            }
            set
            {
                OnUser_modificacionChanging(value);
                ReportPropertyChanging("User_modificacion");
                _User_modificacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User_modificacion");
                OnUser_modificacionChanged();
            }
        }
        private global::System.String _User_modificacion;
        partial void OnUser_modificacionChanging(global::System.String value);
        partial void OnUser_modificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_entrega
        {
            get
            {
                return _Fecha_entrega;
            }
            set
            {
                OnFecha_entregaChanging(value);
                ReportPropertyChanging("Fecha_entrega");
                _Fecha_entrega = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_entrega");
                OnFecha_entregaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_entrega;
        partial void OnFecha_entregaChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_entregaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Hora_entrega
        {
            get
            {
                return _Hora_entrega;
            }
            set
            {
                OnHora_entregaChanging(value);
                ReportPropertyChanging("Hora_entrega");
                _Hora_entrega = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hora_entrega");
                OnHora_entregaChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Hora_entrega;
        partial void OnHora_entregaChanging(Nullable<global::System.TimeSpan> value);
        partial void OnHora_entregaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_devolucion
        {
            get
            {
                return _Fecha_devolucion;
            }
            set
            {
                OnFecha_devolucionChanging(value);
                ReportPropertyChanging("Fecha_devolucion");
                _Fecha_devolucion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_devolucion");
                OnFecha_devolucionChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_devolucion;
        partial void OnFecha_devolucionChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_devolucionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Hora_devolucion
        {
            get
            {
                return _Hora_devolucion;
            }
            set
            {
                OnHora_devolucionChanging(value);
                ReportPropertyChanging("Hora_devolucion");
                _Hora_devolucion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hora_devolucion");
                OnHora_devolucionChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Hora_devolucion;
        partial void OnHora_devolucionChanging(Nullable<global::System.TimeSpan> value);
        partial void OnHora_devolucionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacion
        {
            get
            {
                return _Observacion;
            }
            set
            {
                OnObservacionChanging(value);
                ReportPropertyChanging("Observacion");
                _Observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacion");
                OnObservacionChanged();
            }
        }
        private global::System.String _Observacion;
        partial void OnObservacionChanging(global::System.String value);
        partial void OnObservacionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hotelModel", "ClienteID_", "cliente")]
        public Cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("hotelModel.ClienteID_", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("hotelModel.ClienteID_", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("hotelModel.ClienteID_", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("hotelModel.ClienteID_", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hotelModel", "HabitacionID_", "habitacion")]
        public Habitacion habitacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Habitacion>("hotelModel.HabitacionID_", "habitacion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Habitacion>("hotelModel.HabitacionID_", "habitacion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Habitacion> habitacionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Habitacion>("hotelModel.HabitacionID_", "habitacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Habitacion>("hotelModel.HabitacionID_", "habitacion", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
